spring:
  application:
    name: MoneyTransferApp
  datasource:
    url: jdbc:h2:file:./data/moneytransfer
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
  freemarker:
    suffix: .ftlh
    expose-request-attributes: true
    allow-request-override: true
    settings:
      number_format: computer
  messages:
    basename: messages
    encoding: UTF-8
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
logging:
  file:
    name: logs/moneytransfer.log
